// next-env.d.ts is gitignored and only generated by `next build` / `next dev`,
// so CI's `tsc --noEmit` never sees Next's image module declarations. This
// tracked reference keeps static image imports (e.g. app/(site)/page.tsx)
// type-checkable without a build.
/// <reference types="next/image-types/global" />
